name: Docker Image CI

on:
  push:
    branches: [ "master" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "master" ]

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag $IMAGE_NAME
    - name: Log in to registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
      #run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.io -u ${{ github.actor }} --password-stdin
    - name: Push image
      run: |
        #IMAGE_ID=docker.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=docker.io/scypi1/$IMAGE_NAME
        VERSION=$(echo "${{ github.ref_name }}"
        [ "$VERSION" == "master" ] && VERSION=latest
        echo github.ref=${{ github.ref }}
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION
